mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}
logging:
  level:
    ROOT: info

keycloak:
  realm: test
  host: http://test:8443
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration