DEFAULT_GOAL := help

admin-videos-database:
	docker-compose -f /Users/thiago.resende/projects/fc/codeflix/catalog-admin/sandbox/services/docker-compose.yml up -d mysql


sandbox:
	cd /Users/thiago.resende/projects/fc/codeflix/catalog-videos/sandbox && ./run.sh


