version: "3"

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    depends_on:
      - laravel
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
