version: "3"

services:
  laravel:
    image: tresende/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    depends_on:
      - laravel
    image: tresende/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
