FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY /nginx.conf /etc/nginx/conf.d


RUN mkdir /var/www/html -p && touch /var/www/html/index.php

# docker build -t  tresende/nginx:prod . -f nginx/Dockerfile.prod 
# docker run --rm -it --network laranet --name nginx -p 8080:80 tresende/nginx:prod 