cache:
  type: simple

logging:
  level:
    ROOT: info

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test


elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic


rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    read-timeout: 300
  genres:
    read-timeout: 300
  videos:
    read-timeout: 300
  keycloak:
    read-timeout: 1000