cache:
  type: simple

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    read-timeout: 300
  keycloak:
    read-timeout: 300

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 1

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 300

resilience4j:
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 1
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 100


kafka:
  bootstrap-servers: localhost:29092

spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers}