elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test


kafka:
  bootstrap-servers: localhost:29092

spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers}