apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      app: goserver    
  # replicas: 1
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
        appVersion: "v13"
    spec:
      containers: 
        - name: goserver
          image: "docker.io/tresende/hello-go:latest"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          resources:
            limits: # máximo de recursos que o pod pode usar
              cpu: "500m"
              memory: "25Mi"
            requests: # minimo de recursos que o pod precisa para rodar
              cpu: "100m"
              memory: "20Mi"
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-volume       

          startupProbe:
          #funciona como o readinessProbe, mas é usado para verificar se o pod está pronto para receber tráfego
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 10


          readinessProbe: # verificando se a aplicação está pronta para receber tráfego
          # não deixa as requests  chegarem no pod quando o readinessProbe falha
          # 0/1
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
            # initialDelaySeconds: 10
            # timeoutSeconds: 5

          livenessProbe: # verificando se a aplicação está rodando
          # reinicia o pod quando o livenessProbe falha
            httpGet:
              path: /healthz
              port: 8080
            # initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 1
            successThreshold: 1


      volumes:
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"             