apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
        appVersion: "3"
    spec:
      containers:
        - name: goserver
          image: "tresende/hello-go"