apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - port: 9001 # service port
    protocol: TCP
    name: http-goserver
    targetPort: 8080 # container port
##  kubectl port-forward svc/goserver 9001:9001
## http://localhost:9001/

  # type: NodePort
  # ports:
  # - port: 8080 # service port
  #   nodePort: 30001 # service port
  #   protocol: TCP
  #   name: http-goserver
  #   targetPort: 8080 # container port


##  kubectl port-forward svc/goserver 30001:8080


  # type: LoadBalancer
  # ports:
  # - port: 9001 # service port
  #   protocol: TCP
  #   name: http-goserver
  #   targetPort: 8080 # container port