apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - port: 80 # porta da aplicação
    protocol: TCP
    name: http-goserver
    # targetPort: 8000 
    # kubectl port-forward svc/goserver 8000:8000
