

name: codeflix_rabbitmq

services:
  rabbit:
    container_name: codeflix_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - codeflix_rabbitmq
    profiles: ["admin", "rabbitmq", "all"]

networks:
  codeflix_rabbitmq:
    external: true