name: ci-java
on:
  workflow_dispatch:
  push:
    paths:
      - codeflix/**
      - .github/workflows/ci-java.yml
      
jobs:
  tests:
    name: Tests Runner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      name: Setup JDK 21
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Run application tests
      run: ./gradlew test
